### ISSUE TITLE
FPS drop using drying basin.

### ISSUE THREAD

**Issue by sdaddy** [the-realest-stu/Rustic#1]
Rustic: 0.2
Forge: 13.20.0.2282

I dropped about 20+ frames while next to a drying basin. After the drying was complete the frames shot back up.

Note: If I leave the chunk the basin is in the frames go back up, but if I look back at the chunk they drop again. If I'm inside the chunk the frames drop no matter where I look.

**Comment by the-realest-stu** [comment]
Okay, I might have a solution to this, I might not, I'll have to do some testing.

**Comment by the-realest-stu** [comment]
I have changed evaporating basins to update once per second instead of once per tick, which should hopefully solve this problem. The fix will be part of the 0.3 update.
