### ISSUE TITLE
Optifine shaders aren't working for rustic chiseled blocks

### ISSUE THREAD

**Issue by abcdefplayer** [the-realest-stu/Rustic#103]
When using Chisel Bits (one of the most popular mods) and optifine shaders (any) (same), the *rustic* (slate brick) sides of created block are bugging into rainbow like texture.

**Comment by the-realest-stu** [comment]
Could you provide some more info? Which version of Minecraft, which version of Forge, which version of Optifine, which shaderpack, and also screenshots really help.
