### ISSUE TITLE
mcmod.info file still has the Forge Example text.

### ISSUE THREAD

**Issue by Zarepheth** [the-realest-stu/Rustic#106]
Using the most recent Rustic file "rustic-0.4.3.jar" (as of 2017-Nov-20), MultiMC displays the mod as "Example Mod" in the list of mods for the instance. Digging into the *.jar file and viewing the contents of the "mcmod.info" file shows that the "mcmod.info" file still has the original example text.

I attempted to directly update the mcmod.info file within the *.jar, but Forge encountered an error and refused to load the *.jar. Also, if the issue is not corrected in the source code, the next release will have the same problem.

**Comment by the-realest-stu** [comment]
Fixed in the latest release.
