### ISSUE TITLE
[Suggestion] Inventory Spawning For Wildberries

### ISSUE THREAD

**Issue by InsomniaKitten** [the-realest-stu/Rustic#107]
It would be nice if it tried to place the picked wildberries in the player's inventory slots before falling back to spawning it as an entity in the world.

**Comment by InsomniaKitten** [comment]
Suggested implementation:
```java
if (!player.addItemStackToInventory(stack)) {
    Block.spawnAsEntity(world, pos.offset(player.getHorizontalFacing().getOpposite()), stack);
}
```

Alternatively, `player.inventory.addItemStackToInventory(stack)` will perform the same action, but without an equipping sound.

**Comment by the-realest-stu** [comment]
About to release an update with this included.
