### ISSUE TITLE
Pull request:change the recipe of the iron lattice

### ISSUE THREAD

**Issue by MadRatSRP** [the-realest-stu/Rustic#112]
It has the same recipe as thermal expansion iron gear, i dont want to install NoMoreRecipeConflict so please change its recipe

**Comment by Daihok41** [comment]
Anyone know if the recipe for this is being changed?

**Comment by the-realest-stu** [comment]
It is not going to be changed. It's not hard to install NoMoreRecipeConflict.

**Comment by Daihok41** [comment]
Ok no problem Ill just remove this mod

**Comment by the-realest-stu** [comment]
Again, NoMoreRecipeConflict is super easy to install, and this type of situation is literally the reason it exists, but you do you.
