### ISSUE TITLE
[Bug] CrushingTub.removeRecipe fails

### ISSUE THREAD

**Issue by Tetrajak** [the-realest-stu/Rustic#113]
Minecraft Version: 1.12.2
Forge Build: 2554
Mod Version: 0.4.3

Trying something like the following throws up the error that the method exists but the inputs are wrong. However, it appears to follow the wiki exactly, so have I made a mistake or is there an error in the mod?

CrushingTub.removeRecipe(<rustic:ironberry_juice>, <rustic:ironberries>);

**Comment by the-realest-stu** [comment]
The wiki must not be up to date for the latest version of CraftTweaker. Looking at the CraftTweaker2 wiki, I can verify that you're inputting the fluids as items. Fluids use `<liquid:olive_oil>`, not '<rustic:olive_oil>' (and naturally the same goes for fluids besides olive oil, just replace the fluid name).
