### ISSUE TITLE
Suggestion: Add config option to disable spreading

### ISSUE THREAD

**Issue by ftog-thorgal** [the-realest-stu/Rustic#117]
It would be really nice if you could add an option to the Rustic config to disable Wildberry Bush spreading. I looked through the config and see the options during chunk generation, but I couldn't see anything for spreading once generated.

I really like these bushes for decorating around my buildings, but they just spread too much. If it is something that is easily done, I think it would be awesome to be able to bonemeal the bushes to make then spread (maybe a 1 in 8 chance or something) so when someone disables them via the config and still wants to make more of them.

Thanks for reading, and thanks for a great mod!

**Comment by the-realest-stu** [comment]
I'm releasing an update now that disables natural spreading entirely. Bonemeal will still work, though.
