### ISSUE TITLE
Output liquid in brewing barrel won't budge

### ISSUE THREAD

**Issue by rubenvereecken** [the-realest-stu/Rustic#121]
I can't for the life of me figure out how to remove the wildberry wine and ale I brewed. Bottles are not accepted in the output slot. Buckets are, but they do not interact with the full output liquid tank. No amount of clicking around can make them interact. Next I tried some output fluid pipes so I could get the liquid in a bottler, but nothing.

Is there some regression? Have I somehow not managed the intended behaviour yet?

I'm on rustic 0.4.3 on MC 1.12 and I'd love to help out.

**Comment by the-realest-stu** [comment]
It was working fine with glass bottles last time I checked, so I'm not sure what might be going on. I'll look into it.

**Comment by rubenvereecken** [comment]
Figured it out over Discord!
