### ISSUE TITLE
cannot plant tomato seeds

### ISSUE THREAD

**Issue by mvdhoning** [the-realest-stu/Rustic#122]
tomato seeds cannot be planted
i have placed fertile soil
trying to plant tomato seeds does nothing
placed wooden stake on the soil
trying to plant tomato seeds does nothing
placed more wooden stake on existing stake still no can plant tomato seed
either i have to do something else or something is broken
i am most positive that it is forestry that prevents the tomato seed to be planted

minecraft: 1.12.2
forge: 14.23.1.2566
rustic: 0.4.3

other mods that are be involved
forestry 1.12.2-5.7.0.219

https://github.com/ForestryMC/ForestryMC/issues/1928

**Comment by the-realest-stu** [comment]
works fine for me. Are you clicking the soil or the stake? you have to click the stake.

**Comment by mvdhoning** [comment]
Ah i clicked on the soil not the stake.
Clicking on the stake gets it planted.
But i still have the feeling that without forestry i could click on the soil with stake on it..
