### ISSUE TITLE
Various herbs not needing to be fully grown to yield multiple drops

### ISSUE THREAD

**Issue by Febilian** [the-realest-stu/Rustic#13]
Seems like a dupe bug. Plant an herb on the ground(I'm testing with cohosh for example), immediately break it, get 2-3 in return for the one I just planted seconds ago.

Using Rustic 0.3.1!

**Comment by the-realest-stu** [comment]
Whoops, I'll look into that

**Comment by the-realest-stu** [comment]
Fixed. I'll release a bugfix update in a day or two with this fix and some others
