### ISSUE TITLE
BOP honey conflict

### ISSUE THREAD

**Issue by hologer** [the-realest-stu/Rustic#130]
cant drink honey from a bottle if biomes'o plenty is installed

**Comment by the-realest-stu** [comment]
I can't think of a good way to fix this without breaking honey in existing saves, so I don't think I'll be fixing this. Sorry.

**Comment by Fortist** [comment]
Wouldnt it better to break honey in saves and Fix it overall than to not fix it at all?

**Comment by the-realest-stu** [comment]
Debatable, since drinking honey isn't a particularly important feature
