### ISSUE TITLE
[Compatibility] Metadata check prevents usage of items in crushing tub

### ISSUE THREAD

**Issue by Lordician** [the-realest-stu/Rustic#131]
Greetings. As noted on the Discord:
I am running into a compatibility issue with the mod [Better With Add-ons](https://minecraft.curseforge.com/projects/better-with-addons).
This mod is an add-on to the bigger overhaul mod Better With Mods and adds many features including a food rotting mechanic that i really would like to use.
The problem with this is that this system works by giving food items some metadata regarding their time of creation, for example:
`
<rustic:grapes>.withTag({TimeOfCreation: 288000 as long})
`
I have looked a bit into the code for the cause of this issue and it seems to be related to the metadata check of items that is being done.
Since the grapes have meta data at all in contrary to the grapes in the recipe which have no metadata at all, the grapes are not recognized for the recipe.
Same goes for things like apples, ironberries, olives and wildberries.

I get that a metadata check is necessary for some items but i would love to see a solution to this.
Even if you somehow gave the ability to add a recipe that ignores metadata of items, that would already be enough for this specific case.
I tried working around this  by adding new crushing recipes using Crafttweaker but i have not figured out a good way to do so yet since the time can be a long of many values.
A temporary solution for this for me is disabling the rotting mechanic for these items, but in favor of consistency and things making sense i would love a solution that would not require the disabling of this mechanic.

**Comment by the-realest-stu** [comment]
Sorry for the delayed response, this should be fixed in version 0.4.8, which is awaiting approval on curse right now.
