### ISSUE TITLE
[Bug 0.4.7] Cannot spread berry bushes.

### ISSUE THREAD

**Issue by NotAVerb** [the-realest-stu/Rustic#133]
The almanac states that "Wildberry bushes will not reproduce naturally, but bonemeal can be applied to make them spread." This isn't true. Attempting to use bonemeal on a bush either takes the berries or grows more berries. No new bushes can be generated.

**Comment by the-realest-stu** [comment]
This should be fixed in version 0.4.8, which is awaiting approval on curse right now.
