### ISSUE TITLE
Cannot craft Tiny Pile of Iron Dust into Iron Dust

### ISSUE THREAD

**Issue by ClaudiusMinimus** [the-realest-stu/Rustic#134]
Tiny Piles of Iron Dust cannot be crafted into Iron Dust as stated on https://github.com/the-realest-stu/Rustic/wiki/Materials

PS: I really like your mod and is my modpack I am putting together

**Comment by the-realest-stu** [comment]
Oh, whoops, I forgot to change the wiki. I removed iron dust in the transition to 1.12.

Also, I'm glad you like the mod!
