### ISSUE TITLE
32x Water doesn't fit condensor GUI

### ISSUE THREAD

**Issue by Nazenn** [the-realest-stu/Rustic#14]
If you're using a resource pack and the water in that pack is larger then 16x, it doesn't fit the box allocated for it in the GUI properly and it overhangs to the right. 
Screenshot: https://www.dropbox.com/s/mpnzb74gdbduyc1/2017-05-23_00.18.23.png?dl=0
Minor issue but felt you'd want to know.

**Comment by the-realest-stu** [comment]
Dammit. I didn't want to have to look at that code again, but now I guess I have to.

**Comment by the-realest-stu** [comment]
Fixed! The fix will be included in the next update, which should be released within a few days
