### ISSUE TITLE
Brewing Barrels improperly taking into account culture - FTB Revelations - Rustic Version 0.4.7 - 0.4.8 - MC 1.12.2

### ISSUE THREAD

**Issue by JLDAGH** [the-realest-stu/Rustic#140]
Brewing any of the brewable liquids in the brewing barrel with a culture will substantially decrease quality. For instance, brewing honey with a .75 quality Mead in the culture tank will return .25 quality Mead. The amount of quality the liquid loses is the same every time. 

This is happening on the latest version of FTB Revelations, downloaded through the legacy Windows Launcher. Occurs in single player and multiplayer. Occurs in both versions of rustic I tested, 0.4.7 (0.4.7 is the bundled version of the mod with FTB Revelations) and 0.4.8. Keep in mind, both these versions of rustic were tested while still grouped with the rest of the FTB Revelations mods.

**Comment by Lethann** [comment]
I'm sorta having the same problem but it's not just lowering the quality but completely erasing it so it applied the worst possible mead effect and ended up killing me from wither effect.

**Comment by the-realest-stu** [comment]
Delete anything related to brewing from the config file. Brewing will work as expected afterwards. (The FTB team really needs to read the changelogs when they update mods in their packs.)
