### ISSUE TITLE
[Request] Dimension Blacklist/whitelist for world generation

### ISSUE THREAD

**Issue by Rosethorns** [the-realest-stu/Rustic#141]
As the title implies it would be really helpful to have a dimension blacklist for the purposes of controlling what dimensions Rustic world generation will appear in.

Thanks for reading my request.

**Comment by the-realest-stu** [comment]
Makes sense. I plan on doing a small update within the next week or two, so I'll probably implement this then.

**Comment by the-realest-stu** [comment]
I added 2 config options for this: a whitelist for overworld dimensions, and a whitelist for nether dimensions. Rustic's overworld world gen will only happen in dimensions in the overworld whitelist, and it's nether world gen will only happen in dimensions in the nether whitelist. By default, each list only contains the respective vanilla dimension. I hope these options allow you to accomplish whatever you wanted to do, but if they don't then I can change them.
An update with the new config options is now available on curseforge.

Big fan of your videos, by the way.

**Comment by Rosethorns** [comment]
That sounds perfect. Thank you so much
