### ISSUE TITLE
Stair lighting black patches with OptiFine

### ISSUE THREAD

**Issue by Lorelando** [the-realest-stu/Rustic#142]
Stairs added by Rustic produce black patches when running alongside OptiFine. This does not happen for vanilla stairs.

![2018-02-16_23 21 24](https://user-images.githubusercontent.com/19599163/36331983-7ddb4cec-1370-11e8-8ed0-d963a91ead0e.png)

Minecraft 1.12.2
Forge 14.23.2.2611
Rustic 0.4.8
OptiFine HD_U_C9

#116 might be the same issue

**Comment by the-realest-stu** [comment]
This is in fact a duplicate issue of #116.
