### ISSUE TITLE
[Request] Tweak Rustic fluids to behave themselves better with water

### ISSUE THREAD

**Issue by NotAVerb** [the-realest-stu/Rustic#149]
I'm not sure how it's being done, but Rockhounding Surface proves that this behavior is possible. The red liquid is wildberry juice, the other is wood aging bath.
I think that the Rockhounding fluids might be set to spread slower than the water can replenish itself. Thus preventing dehydration.
![2018-02-25_07 29 21](https://user-images.githubusercontent.com/30223331/36641479-cdbb5a5a-1a27-11e8-8b66-f3941d07d184.png)

**Comment by NotAVerb** [comment]
It doesn't actually seem to be an issue of speed, as my vertical honey test comparison just displayed.
I should mention that the Rockhounding fluids do in fact spread into the water. They get replaced by water and spread back again in a loop.
![2018-02-25_07 54 08](https://user-images.githubusercontent.com/30223331/36641641-019677a8-1a2b-11e8-8d90-5bb583da7542.png)

**Comment by the-realest-stu** [comment]
This behavior is actually intentional; I won't be changing it.
