### ISSUE TITLE
[0.4.10] Brewing wont increase Quality

### ISSUE THREAD

**Issue by Thalaan** [the-realest-stu/Rustic#152]
Hello,

example: brewing capacity first slot Wine Quality 0.25 and after 10+ brewing attempts the output was always 0.24

in version 0.4.8 it works flawless and it increases step by step

**Comment by the-realest-stu** [comment]
Whoops, not sure why I changed the logic behind that. I guess I was too tired to think clearly when I did it. Anyway, it will be fixed in the next release, which should be soon.

**Comment by the-realest-stu** [comment]
Just released the update.
