### ISSUE TITLE
Dynamic trees compat not working

### ISSUE THREAD

**Issue by Voxel-Friend** [the-realest-stu/Rustic#153]
Crashes the game with only rustic 1.0.0 and Dynamic trees 0.7.4 installed

https://gist.github.com/Voxel-Friend/bd64bf805dcfd8118a26b8572ab7599d

**Comment by Lorelando** [comment]
All tests done with
Minecraft 1.12.2
Forge 14.23.2.2611
Rustic 1.0.0

Client crashes when _Dynamic Trees 0.7.4_ is installed
https://gist.github.com/Lorelando/6b2037776192ad6c2d1932669966c498

Client does not crash when _Dynamic Trees 0.7.5a_ is installed

Server crashes when either _Dynamic Trees 0.7.4_ or _Dynamic Trees 0.7.5a_ is installed (didn't test earlier versions)
DT 0.7.4: https://gist.github.com/Lorelando/9ae47db8a0b571299f12a4a9af9f35f6
DT 0.7.5a: https://gist.github.com/Lorelando/4316e46737abecd896a376904a2afc97

**Comment by the-realest-stu** [comment]
The client compat requires 0.7.5a (or probably higher, until a future Dynamic Trees update breaks the current compat). I just fixed the server crash, and released an update on curseforge. I've also made sure that attempting to use a Dynamic Trees version below 0.7.5 should actually notify the user that they need a newer version.
