### ISSUE TITLE
[suggestion] dynamic wildberry bushes

### ISSUE THREAD

**Issue by majijn** [the-realest-stu/Rustic#156]
is it too late to ask for them? 
it would add something dynamic trees doesnt have which is bushes.

**Comment by Lorelando** [comment]
I think this would better fit directly into Dynamic Trees, as it probably (to properly fit the scale) would require some new behavior where leaves can also be counted as branches, or a combination of leaves and branches.

However, it would be really nice for wildberry bushes to have growth stages and a spread behavior.

**Comment by NotAVerb** [comment]
Wild berry bushes used to spread a few versions ago, but this functionality was removed. I believe it was because they were too common a food source, but that's my speculation.

**Comment by majijn** [comment]
lorelando did you miss the part where if dynamic trees is installed rustic lets you get dynamic versions of olive trees and ironwood trees? 

anyway it would be LOVELY if we could get wildberry bushes that we could trim and shape a little bit 

; notaverb im not sure why you're talking about that here? (also if you want to spread them use bonemeal on bushes with fruit, and they'll spread to the 8 blocks immediately around them.)

**Comment by Lorelando** [comment]
@majijn no, I did not. 
What I am saying is that Dynamic trees doesn't have bushes. If it did, and hat an API to add new bushes, it would make sense to support that feature.

**Comment by the-realest-stu** [comment]
I wildberry bushes are only ever meant to be a single block in size, and I don't plan on changing that.

**Comment by majijn** [comment]
that's fair, thought id ask just in case!

thanks for the work you put into the dynamic olive and ironwood trees, they're beautiful!
