### ISSUE TITLE
Crash with What's That Slot

### ISSUE THREAD

**Issue by InsomniaKitten** [the-realest-stu/Rustic#16]
Crash during game startup, "Empty string not allowed".

**Mod version:** [0.3.1](https://minecraft.curseforge.com/projects/rustic/files/2423010)
**WTS version:** [1.0.1](https://minecraft.curseforge.com/projects/whats-that-slot/files/2347635)
**Forge version:** [1.11.2-13.20.0.2285](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2285/forge-1.11.2-13.20.0.2285-changelog.txt)

**Crash report:** [paste.ee/XKmm9](https://paste.ee/p/XKmm9)

**Comment by the-realest-stu** [comment]
Ooh, never heard of that mod, it seems nice! I'll try to get this fixed for the bugfix release that I plan on releasing soon.

**Comment by the-realest-stu** [comment]
Fixed! The fix will be included in the next release, which should happen within the next few days
