### ISSUE TITLE
Using Booze Culture Heavy Decrease Quality

### ISSUE THREAD

**Issue by The-Mad-Cat** [the-realest-stu/Rustic#162]
Using booze culture heavy decrease quality. From the Brewing Wiki it states it should give between -0.01 to +0.04 from culture booze's quality. I'm getting all time -0.50 from culture booze's quality. Base off the config file it agree with poor quality. See the config file setting below. It's odd that "default" was as -50. My question is this a bug in rustic or miss configuration in FTB Revelation v1.5.0?

From the Config File Below. 
```
# the minimum amount of increase that booze culture will provide to the new brew, in percent [range: -1 ~ 50, default: -50]
I:"Minimum Increase To Brew Quality"=-50

# the maximum amount of increase that booze culture will provide to the new brew, in percent [range: 4 ~ 50, default: -50]
I:"Maximum Increase To Brew Quality"=-50
```

**Comment by the-realest-stu** [comment]
Just delete those config options and let the game regenerate them, or manually update the mod (the newer versions will automatically fix the config if it's broken in this way)

**Comment by The-Mad-Cat** [comment]
Thank You for your information. Deleting config didn't seem to help. However, I upgraded fresh copy of FTB Revelation 1.8.0 which seem to fix the problem. I would assume editing the config would also fix the problem.
