### ISSUE TITLE
Compilation instructions

### ISSUE THREAD

**Issue by atakle** [the-realest-stu/Rustic#163]
Since Dynamic Trees compatibility was added, compiling Rustic seems to require manually adding it as a dependency somehow. I couldn't figure out how to make it work, and it would be nice if it was documented somewhere.

**Comment by atakle** [comment]
I figured it out. Create a folder named "libs", download the correct version of Dynamic Trees and drop it in that folder. The correct version of Dynamic Trees is 0.7.5a or above, as described in issue #153.

Although I still think better documentation would be good.

**Comment by the-realest-stu** [comment]
Adding a dependency to the dev environment is more of a general mod dev thing, not specific to this mod. As such, I don't think this is the right place to document how to do that.
