### ISSUE TITLE
Fluid bottles should hold 250 mb instead of 1000 mb

### ISSUE THREAD

**Issue by WrongWeekend** [the-realest-stu/Rustic#165]
Going by vanilla cauldron standards (and those set in most tech mods with fluid/container machines) the bottle should hold 1/4 as much as a bucket, not the same amount. In the case of picking up in-world fluid blocks, it also makes sense to have a narrow-necked bottle be a highly lossy tool for recovery compared to a bucket.

**Comment by the-realest-stu** [comment]
Even within vanilla there are conflicting standards for how much liquid a bottle should hold.
Having Rustic's bottles hold an entire bucket makes things simpler, so I don't intend to change it.
