### ISSUE TITLE
Culture tank in brewing barrel not working

### ISSUE THREAD

**Issue by nemba246** [the-realest-stu/Rustic#169]
I've put in 0.7 quality Ale into the culture tank and I've gotten only 0.2 quality after putting some Ale wort in. I also tried putting 0.43 quality ale and I got 0.0 quality ale from putting ale wort in. This issue also occurs with mead. 

I'm currently running rustic 0.4.8 in a multiplayer FTB revelation 1.6.0 server

![2018-04-03_15 10 32](https://user-images.githubusercontent.com/28603391/38278738-1f15e70c-3752-11e8-9051-237b69b83aa6.png)
![2018-04-03_15 10 35](https://user-images.githubusercontent.com/28603391/38278739-1f335cd8-3752-11e8-9ee1-2bf6aa72ed92.png)

**Comment by the-realest-stu** [comment]
Just delete the options related to brewing in Rustic's config file and let the game regenerate them, or manually update the mod (the 'newer' versions will automatically fix the config if it's broken in this way)
