### ISSUE TITLE
Mod interferes with void generation.

### ISSUE THREAD

**Issue by Eliwood** [the-realest-stu/Rustic#17]
At least, that's the closest thing I can tell.  I'd really wanted to include this mod in a skyblock pack I was creating, but got stumped when, after adding Rustic, world creation hangs on the "loading world" text.  The debug log shows no change after 5 minutes of waiting.

I was using Void Island Control for void generation.  And just to make sure, I made a pack containing only the two mods mentioned, and the same series of events occurred: upon attempting to create a new world, minecraft hangs on the "loading world" text.  No change in the debug log.

Hopefully this can be fixed?  I'm not 100% sure that it's even an issue, nor am I sure whether this'd be easy to fix.  But I figured I'd put in my feedback.

Cheers!

**Comment by the-realest-stu** [comment]
Thanks for the bug report! I'll have to do some testing to see what might be going wrong, but thankfully I dont have too many worldgen classes to look through. You may have to wait a little but for a fix though, as I just released a patch a few hours ago, and I'd prefer to wait a few days to allow for more bugs to be reported.

**Comment by the-realest-stu** [comment]
Fixed! I'll release an update now!
