### ISSUE TITLE
Two bugs regarding the brewing barrel

### ISSUE THREAD

**Issue by hottentottententententoonstelling** [the-realest-stu/Rustic#171]
I'm using the latest version of both Rustic and forge 1.12.

The first bug only happens if forestry is registered. Since forestry also uses honey as fluid, the brewing barrel does not accept honey (from Rustic) as fluid anymore.

The second bug is that the brewing barrel no longer accepts glass bottles and buckets to get the fluids out of the brewing barrel.

Thanks in advance if you can fix these two bugs!

**Comment by CherryGryffon** [comment]
Having this issue myself, the liquid just sits there. Very little is on the server, the highlight is meant to be the Rustic mod itself. Is there a workaround?
