### ISSUE TITLE
Brewing Barrel not filling glass bottles when EnderCore is installed

### ISSUE THREAD

**Issue by Seathes** [the-realest-stu/Rustic#172]
Ran into an issue where it is not possible to get fluids out of the brewing barrel when also using forestry. Was able to input honey and ferment to mead, but glass bottles and buckets do not take it out of the barrel either by right clicking or by placing container in slot.

**Comment by wooby6** [comment]
Got the same issue but with [EnderCore](https://minecraft.curseforge.com/projects/endercore)

**Comment by nunavailabul** [comment]
Also have this issue with Ender Core / Ender IO.

**Comment by the-realest-stu** [comment]
This might be fixed in 1.0.5, which I just uploaded to curseforge. I haven't been able to recreate the bug, so I can't test it, so please let me know if it works.

**Comment by wooby6** [comment]
the issue with EnderCore is Fixed, Haven't tested forestry

**Comment by wooby6** [comment]
@hottentottententententoonstelling You are correct these same issues still affect EnderCore, thanks for point that out i Hadn't tested those

**Comment by the-realest-stu** [comment]
@hottentottententententoonstelling 
1. Extracting honey from the tub with a bucket should still work with Forestry, but bottles can't store Forestry honey. I guess I might change that in the next update.
2. So are you saying you still can't extract fluids from the output of brewing barrels?
3. Can you elaborate on what you mean regarding the icons not rotating properly? I haven't heard about that before.

**Comment by hottentottententententoonstelling** [comment]
1. Thanks, I will check if the buckets work for me
2. I can't extract the fluids from the left fluid inventory (which determines the range of the new brew)
3. Before having these issues, the icons at the top where you place the bottles/buckets, you saw these two icons switching between each other. That part is missing now where the first two show buckets and the last one a bottle

**Comment by the-realest-stu** [comment]
The bottle/bucket icons should no longer switch (at least for the output slots) because I removed the ability to use buckets with the output tank (none of Rustic's alcoholic fluids can be held in buckets anyway).

**Comment by hottentottententententoonstelling** [comment]
Then the first icon should be a bottle and this is currently a bucket

**Comment by the-realest-stu** [comment]
Ah, whoops. I'll fix that.

**Comment by viveleroi** [comment]
With 1.0.6, the only remaining issue as far as I can tell is that the left-most fluid (the "starter" essentially) can't be taken out. I'm not having any of these other problems and I have both EnderCore and Forestry, so I assume they've been fixed.

**Comment by hottentottententententoonstelling** [comment]
There are still two issues present, first the reference tank (left tank) can't accept bottles into its input slot to remove the reference brew (but you can destroy the barrel to do so). Secondly the icon of the input slot of the middle tank is still a bucket (instead of both a bottle and bucket or only a bottle).

**Comment by the-realest-stu** [comment]
Fixed in version 1.0.12
