### ISSUE TITLE
CRASH ON LAUNCH

### ISSUE THREAD

**Issue by iobiarg** [the-realest-stu/Rustic#173]
Hi there. It's been a while.
I quited minecraft in January but i'm back and of course i want your mod, especially knowing you updated it. But you mod is asking for Dynamic Trees 1.12.2-0.7.7, witch seems to be an alpha that makes my game crash on launch. Is there any fix to this? is it a problem with my other mods? I'm not a programmer so I don't get the mistake besides it says there is an error on launching dynamictressbop

[crash-2018-05-08_12.34.40-client.txt](https://github.com/the-realest-stu/Rustic/files/1984641/crash-2018-05-08_12.34.40-client.txt)
If I use the 1.12.2-0.7.6 the game starts but it cant launch rustic...
Thanks in advance, if this is a problem to be told to dynamic trees developers i'm sorry for wasting your time.

**Comment by ferreusveritas** [comment]
Update dynamictreesbop to version 1.1.0a
Also you should update Dynamic Trees again since I just fixed a major bug a few minutes ago.

**Comment by iobiarg** [comment]
I just did.. you aswered me in the other github XD I'll download that right now. thanks for the aswer, u are lovely
