### ISSUE TITLE
crash when liquid barrel has fluids in it in chest inventory

### ISSUE THREAD

**Issue by Divineaspect** [the-realest-stu/Rustic#175]
crash when liquid barrel has fluids in it in chest inventory
https://pastebin.com/WXgCCa5L
https://gist.github.com/Divineaspect/22c82bf7a997de4dddf5cf6fb5556319

**Comment by Divineaspect** [comment]
better gist with all the files when duplicating crash having removed inventory tweaks which seemed to be incriminated.
https://gist.github.com/Divineaspect/27e1e853d1ecdb765ab814b350ce988f

**Comment by the-realest-stu** [comment]
This might be fixed in 1.0.5, which I just submitted on curseforge. Please let me know if it does when you're able to test it out.
