### ISSUE TITLE
Brewed Ale/mead/... in Barrel loses Quality

### ISSUE THREAD

**Issue by MacBath** [the-realest-stu/Rustic#177]
Hi,

dont know if it's only me but im playing FTB revelation MC 1.12.2 and startet to use the rustic brewing.
Whenever i put my alcohol (e.g. Mead Quality 0.68) in a barrel it loses it's Quality
Would be nice of you to fix that thx.

**Comment by KorDum** [comment]
I see the same behavior.
+1

**Comment by the-realest-stu** [comment]
@MacBath either update the mod to a more recent version or delete rustic.cfg in the config folder.
@KorDum you can try the same thing if you're also using an old version of the mod, but otherwise you might just be really unlucky.
