### ISSUE TITLE
[Question] How can I remove recipes from Condenser?

### ISSUE THREAD

**Issue by KorDum** [the-realest-stu/Rustic#178]
I saw the wiki
https://github.com/the-realest-stu/Rustic/wiki/CraftTweaker-Support
but I can't remove all Elixirs of Speed:
```
import mods.rustic.Condenser;
Condenser.removeRecipe(<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:swiftness"}]}));
Condenser.removeRecipe(<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:strong_swiftness"}]}));
Condenser.removeRecipe(<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:long_swiftness"}]}));
```
or
```
import mods.rustic.Condenser;
Condenser.removeRecipe(<rustic:elixir>.withTag({ElixirEffects: [{Effect: "swiftness", Duration: 1800, Amplifier: 0}]}););
```
do nothing without errors (in crafttweaker.log):
```
[INITIALIZATION][CLIENT][INFO] Removing Condenser Recipes for Item Elixir of 
```

**Comment by KorDum** [comment]
Or can I remove Alchemy (sorry, too imbalanced) from config file?

**Comment by the-realest-stu** [comment]
The first way you described won't work, but the second one should if you replace `Effect: "swiftness"` with `Effect: "minecraft:speed"`. You can use the command `/ct hand` while holding an elixir in you main hand to get the proper item tag to use in the script.

**Comment by KorDum** [comment]
Cool, thanks!
