### ISSUE TITLE
Bucket Duplication Glitch

### ISSUE THREAD

**Issue by Nazenn** [the-realest-stu/Rustic#18]
If you put in a single bucket of a brewable fluid such as apple juice into the Brewing Barrel, it fills up entirely and spits 8 buckets back out at you.

Using Rustic 0.3.2

**Comment by the-realest-stu** [comment]
Dammit, I never see that in my Dev environment anymore! I thought that was working!
Adding that to the list of bugs to fix for the next release.

**Comment by the-realest-stu** [comment]
I can't seem to replicate this bug in the dev environment, but I do experience it outside of the dev environment. Basically, I have no idea what to do about it. Dammit.

**Comment by Staebchen** [comment]
Sadly it makes the brewery unusable. :(

**Comment by the-realest-stu** [comment]
Well, I mean, kinda. It still works, it just duplicates fluids and buckets. If you wanted, you could get 8 buckets of fluid and trash the remaining 7. Of course, that doesn't make fixing the bug any less of a priority for me.

**Comment by the-realest-stu** [comment]
Oh thank god! It was an easy fix. I was comparing stacks to ItemStack.EMPTY, because I wrote that code before the helpful post on r/ftb about why that's a bad idea.

**Comment by the-realest-stu** [comment]
I'll release a bugfix update soon to fix this.
