### ISSUE TITLE
Ender IO Farming Station Berry Bush Crash

### ISSUE THREAD

**Issue by NillerMedDild** [the-realest-stu/Rustic#180]
One of my users reported a server crash, when his Ender IO Farming Station attempted to harvest a Rustic Berry Bush. I don't know which mod has the responsibility, so I'm reporting this on both trackers.

Crashlog: https://pastebin.com/bYBmD9NX

Minecraft 1.12.2
Forge 1.12.2-14.23.4.2705
EnderCore-1.12.2-0.5.31
EnderIO-1.12.2-5.0.26
rustic-1.0.5

**Comment by tyler489** [comment]
This was caused by redurecting a call to a seed item into a block. Since henry was unable to find  documentation about this on forge enderio has built in a fix
