### ISSUE TITLE
Feather potion not working

### ISSUE THREAD

**Issue by Elmfeather7** [the-realest-stu/Rustic#181]
Okay so im using 1.11.2 the most recent updated version of rustic for this version. I've just tried to drink some feather potions and nothing happens, i drink it and i dont get a buff, nothing slows down when i fall off great heights too.

**Comment by the-realest-stu** [comment]
Could be an old bug where elixirs don't work unless they're in a stack of at least 2 items. If not, it's hard to say what the problem might be with the limited amount of information you provided.
