### ISSUE TITLE
Config for Disabling Ironberries

### ISSUE THREAD

**Issue by NillerMedDild** [the-realest-stu/Rustic#186]
Hey! I'd really like the ability to disable Ironberries from dropping from Ironwood trees, maybe even a config to disable them from the registry - I'm making a modpack where I don't want players to have access to anything that sounds metal related early on, but still have access to Ironwood Trees.

I hope you'll consider it :)

**Comment by the-realest-stu** [comment]
I'd suggest  using CraftTweaker to remove the ironberry juice -> iron dust drying recipe, and also to change the display name of ironberries (and the juice/wine, if CT can rename fluids) to something not related to iron.

**Comment by NillerMedDild** [comment]
Alright.
