### ISSUE TITLE
Entities can't path around most blocks

### ISSUE THREAD

**Issue by plausibleusername** [the-realest-stu/Rustic#188]
Wildberry bushes, candles, and pretty much any block that isn't totally solid confuses the AI badly. My villagers keep trying to walk through bushes and get stuck there until I push them out or break the bush. Other entities seem to be affected too.

**Comment by Laike-Endaril** [comment]
I've run into this as well.  It causes issues with combat in my modpack, so I'm removing Rustic from the mix for now.  Too bad; I like some of the decoration it adds :/

You can easily encounter this issue by standing on the opposite side of a bush from a creeper.

**Comment by the-realest-stu** [comment]
Fixed in version 1.1.0

**Comment by Laike-Endaril** [comment]
@the-realest-stu Awesome, will try adding it back in then!  If you don't see a new issue from me within a month then it's working well enough for me XD
