### ISSUE TITLE
Wildberry Wiki Page is inaccurate

### ISSUE THREAD

**Issue by plausibleusername** [the-realest-stu/Rustic#194]
For quite some time, I've been trying to multiply berry bushes with the method described on the wiki. After some frustration and no success, I decided to read through old issues to see if it was a bug or if the wiki was wrong. As it turns out, natural berry bush growth has been removed and the only way to grow more is now bonemeal, which the wiki contains no hint of. This should probably be corrected.

**Comment by the-realest-stu** [comment]
Fixed
