### ISSUE TITLE
Ironwood and Olive Logs not registered in OreDict as Log

### ISSUE THREAD

**Issue by Staebchen** [the-realest-stu/Rustic#20]
Ironwood and Olive Logs are not recognised as logs, and are ,for example, not able to be broken by standard Tree feller/chopper mods. Possibly a problem with the oredictionary (?)

Planks can also not be used for the Crafting Table or Sticks

**Comment by the-realest-stu** [comment]
I tested it in and out of a dev environment, and my planks can be used for both crafting tables and sticks. My logs also extend the vanilla log class, and are oredicted properly as logs, so the problem isn't on my end. You may just have to add my logs to a config, or something. I tested them with the timberjack mod, and it worked fine, even without changing configs.

**Comment by Staebchen** [comment]
Thanks, I will switch to the Timberjack mod then and try again!
