### ISSUE TITLE
[Texture] Fertile Soil

### ISSUE THREAD

**Issue by TimGoll** [the-realest-stu/Rustic#206]
I noticed a small problem when using your Mod with a texture pack. The upper side of the Fertile Soil block gets the new dirt texture while the other five sides stay with a texture which looks a bit like the default dirt texture.

![image](https://user-images.githubusercontent.com/13639408/44628070-ae760400-a939-11e8-8d53-e90055794e38.png)

**Comment by the-realest-stu** [comment]
Not a bug. Fertile soil uses a custom texture for the sides of the block.
