### ISSUE TITLE
Juices and Alcohols not registered as Foods

### ISSUE THREAD

**Issue by Staebchen** [the-realest-stu/Rustic#21]
Juices and Alcohols seem to not be registered as Foods.
e.g.: They do not register with the apple skin mod.

It's possible that they are registered as potions instead?

**Comment by the-realest-stu** [comment]
This is on purpose. Juices and alcohols are stored in bottles, and the bottle item is not an ItemFood.

**Comment by Staebchen** [comment]
ok! Good to know. :)
