### ISSUE TITLE
Beehives break on block update, even if attached to leaves

### ISSUE THREAD

**Issue by DaedalusGame** [the-realest-stu/Rustic#212]
Seems to happen for modded and vanilla leaves, but could potentially be an interaction, haven't looked at the beehive code

**Comment by netmc** [comment]
This issue is more prevalent with dynamic trees.  As the trees grow,  the hives break and the bees fall to the ground.  You end up losing out on bees quite a bit if you aren't in a new area.

**Comment by the-realest-stu** [comment]
Fixed in version 1.0.12
