### ISSUE TITLE
Cannot open the GUI of the advanced condenser

### ISSUE THREAD

**Issue by wormzjl** [the-realest-stu/Rustic#213]
So I've built the adv. condenser as shown on the wiki, but I cannot open the gui.
The normal version works fine.
rustic-1.0.9

**Comment by the-realest-stu** [comment]
Do you have three advanced retorts attached?

**Comment by migmolrod** [comment]
That was it in my case, thank you @the-realest-stu 
My bad, I didn't RTFM XD
