### ISSUE TITLE
Dynamic Trees and Apple Pips

### ISSUE THREAD

**Issue by netmc** [the-realest-stu/Rustic#220]
It seems when using the Apple pip for dynamic trees, it grows into an oak tree with oak leaves (according to waila)  The vanilla style sapliing grows with oak wood and apple leaves.  This is in 1.0.9.  I've left the tree growing for some time and even used some bone meal on the root block, but no apples ever formed.

Edit:  I just look again, and Rustic does have the apple sapling, but is the apple pip from Rustic or Dynamic Trees?

**Comment by the-realest-stu** [comment]
The apple pip is from Dynamic Trees. The lack of apple growth is/was an issue from Dynamic Trees that should be solved in the latest alphas.
