### ISSUE TITLE
Alchemic condenser cares too much about NBT data

### ISSUE THREAD

**Issue by darloth** [the-realest-stu/Rustic#222]
I'm using Foodfunk, which adds NBT data to food to track how long it takes to rot.

The alchemic condenser is (apparently) extremely picky, and won't take any food items as a result of this.  If I set the item to not rot in Foodfunk and pull a fresh one with no NBT data, that item is usable, but ideally the condenser shouldn't care about extra nbt tags on its ingredients and just use them anyway? None of the default receipes seem to have a use for nbt data on the inputs, at least, so I would assume it could just discard the data.

**Comment by the-realest-stu** [comment]
Fixed in version 1.1.0
