### ISSUE TITLE
Weird latice vertical down connection with horizontal chains

### ISSUE THREAD

**Issue by LemADEC** [the-realest-stu/Rustic#228]
As of 1.0.13, a latice will render as connected vertically down when an horizontal chain is placed below.
For example, on below pictures, the red part seems a bit off:
![image](https://user-images.githubusercontent.com/4776032/49346756-4309a400-f697-11e8-80a7-7cfe1b5b2bfe.png)

**Comment by the-realest-stu** [comment]
Fixed in version 1.1.0
