### ISSUE TITLE
Dynamic Trees Hard Dependency?

### ISSUE THREAD

**Issue by gggg336** [the-realest-stu/Rustic#229]
Updated Rustic to 1.0.14 and a crash happened where it is referencing Dynamic Trees class files. I don't have the mod installed and I understand it is supposed to be a soft dependency or is that changing?

Crash report: https://paste.ee/p/JLy9z

**Comment by DWX12** [comment]
Can concur, I have the same crash. I assume it's just something that was made in error:
https://hastebin.com/vonixufadi.sql

**Comment by MokahTGS** [comment]
Please remove the hard dependency on Dynamic trees...causes all sorts of confusion.

**Comment by ferreusveritas** [comment]
I can't remove it from an already posted version.  Just downgrade until the next version.

**Comment by the-realest-stu** [comment]
Fixed in 1.0.15
