### ISSUE TITLE
Honey and Biomes o Plenty

### ISSUE THREAD

**Issue by Fortist** [the-realest-stu/Rustic#234]
You already know, but to reiterate that fact and I cant even brew mead at the moment.
Gonna do a lot of crafttweaking to make both mods not absolute shit.

**Comment by ferreusveritas** [comment]
Calm down.  Rustic is not "absolute shit" just because it doesn't work how you want it to in this particular circumstance.  We work hard on these mods for basically nothing.  Show some appreciation.

**Comment by the-realest-stu** [comment]
Honey from Biomes O Plenty actually can be used to brew mead. I just double checked.
Are you using the latest version of Rustic?
