### ISSUE TITLE
Drinking milk from non vanilla bucket (e.g. Ceramics) still cures inebriation 

### ISSUE THREAD

**Issue by KnightMiner** [the-realest-stu/Rustic#235]
Currently, if you use an item that applies the milk cure effect without being a milk bucket, it is able to cure inebriation. Looking at the code, it seems to be because of the weird way you make the effect incurable. Specifically, you are checking for [the player drinking milk](https://github.com/the-realest-stu/Rustic/blob/master/src/main/java/rustic/common/potions/EventHandlerPotions.java#L25-L38) to remove the curative items instead of just removing them when adding the effects.

You could easily solve this by doing what I did in SimplyTea by just removing the [curative items from the potion itself](https://github.com/elucent/SimplyTea/blob/master/src/main/java/elucent/simplytea/potion/PotionCaffeinated.java#L18-L22). For the negative effects caused by Inebriation, just remove the curative items [when the effects are added](https://github.com/the-realest-stu/Rustic/blob/master/src/main/java/rustic/common/potions/PotionTipsy.java#L17-L24). This also removes the side effect of drinking milk while inebriation causing normally curable effects to be incurable.

Using Rustic 1.0.15 if it helps, but the code snippets are probably better than that.

**Comment by the-realest-stu** [comment]
Fixed in version 1.1.0. Thanks for the help!
