### ISSUE TITLE
Deathstalk mushroom recursion

### ISSUE THREAD

**Issue by FallenEagle1** [the-realest-stu/Rustic#239]
Modpack: All the Mods 3
Rustic: 1.0.12

Not exactly sure how this crash report came about, it was asked about in a discord channel, so just passing it along. It looks like there is a function being recursively called, without a solid termination? 
https://gist.github.com/Ovie105/a52dee46f2f937c3f3256d835ac98c03

Not sure if it's easily repeatable, or if an update will fix it, was running out of time for testing and wanted to pass it along before it was forgotten.

**Comment by the-realest-stu** [comment]
duplicate of #238
