### ISSUE TITLE
Fix mobs trying to pathfind on top of berry bushes since new bounding box change

### ISSUE THREAD

**Issue by Corosauce** [the-realest-stu/Rustic#242]
Just needs to have BlockBerryBush.isPassible return true, puts the pathfinders expectations in line with the fact the block has no bounding box now.

Currently they are trying to jump on top of them, then fall through and get stuck and keep jumping, breaking pathfinding.

![2019-02-13_11 17 34](https://user-images.githubusercontent.com/1238621/52726431-2d5f0780-2f81-11e9-8fc6-ec9e9b8007ed.png)

**Comment by the-realest-stu** [comment]
Fixed in version 1.1.1
