### ISSUE TITLE
Performance Issues with Alchemy Condensers that have Full Slots

### ISSUE THREAD

**Issue by Luke616** [the-realest-stu/Rustic#243]
Hello,

I've been running a server for a modpack with Rustic in it and have been periodically performing CPU time profiles using the mod [LagGoggles](https://minecraft.curseforge.com/projects/laggoggles). I've noticed a performance issue which stems from Alchemy devices that have items in each slot, but are not currently brewing elixirs.

![2019-02-14_12 57 37](https://user-images.githubusercontent.com/3951604/52809587-a3856c00-305e-11e9-8483-f31fdd279b4e.png)
![2019-02-14_12 58 07](https://user-images.githubusercontent.com/3951604/52809591-a54f2f80-305e-11e9-9b6e-0c047b5ea4b0.png)
![2019-02-14_12 58 21](https://user-images.githubusercontent.com/3951604/52809597-a8e2b680-305e-11e9-8f92-aff1f9107825.png)
![2019-02-14_12 58 23](https://user-images.githubusercontent.com/3951604/52809600-aaac7a00-305e-11e9-8164-7b1ee6bf9c33.png)

This issue occurs with both standard and advanced alchemy condensers. If all slots are full, as shown in the screenshots above, the condensers will tick rapidly and cause up to ~750 us/tick worth of lag. After testing for a bit I've found this to be consistent. If either the bottles, inputs, or fuel slots are emptied, the lag does not occur and the condensers contribute a much more manageable ~5 us/tick. If all slots are emptied, the condensers contribute nothing to the server load whatsoever.

I understand if this is difficult or impossible to fix in the short term. Let me know if you'd like any more information about the issue.

Using:
Rustic 1.0.15
Forge 14.23.5.2808

Thanks much,
Luke616

**Comment by majijn** [comment]
https://github.com/the-realest-stu/Rustic/issues/184
