### ISSUE TITLE
Brewing - Quality 

### ISSUE THREAD

**Issue by DFrry** [the-realest-stu/Rustic#244]
Whenever I'm brewing, the quality of the resulting ale is going over 0.75. Is this a bug, or how it's supposed to be? Either way, is there any benefit of having ale with a quality higher than 0.75?

**Comment by EchoingZen** [comment]
Not a bug. By default, you can only get wines from 0.05 to 0.75, but if you brew wines with a seed wine, you can get all the way up to 1.0, which is the best.

**Comment by the-realest-stu** [comment]
Yup, that's exactly how brewing is meant to work
