### ISSUE TITLE
[Bug] Wildberry bushes generate underwater

### ISSUE THREAD

**Issue by CREEATION** [the-realest-stu/Rustic#245]
This causes many entities being dropped.

![2019-03-17_23 43 10](https://user-images.githubusercontent.com/3277769/54499215-8f5bb580-490f-11e9-96c2-9ba910ea618f.png)
![2019-03-17_23 42 59](https://user-images.githubusercontent.com/3277769/54499220-9c78a480-490f-11e9-9b3b-894e74080171.png)

**Comment by the-realest-stu** [comment]
Should be fixed in version 1.1.1
