### ISSUE TITLE
World corrupting crash with grapes and iron lattices

### ISSUE THREAD

**Issue by RivusTheFerret** [the-realest-stu/Rustic#248]
This bug can be re-created without fail by growing grapes onto a piece of rope that is adjacent to an iron lattice. This will immediately cause a crash; attempting to load back up the world will also result in a crash until the Rustic jar file is removed from the mods folder.

I specifically found this bug in the modpack "Roguelike Adventures and Dungeon" by xDreamz on the twitch launcher. The pack uses Minecraft version 1.12.2 and Rustic version 1.1.0 (which I believe is the most updated version)

Included is a paste bin of the crash log:
https://paste.dimdev.org/makuxodoxu.mccrash

Other information:
I am playing on a lan server which I am hosting
I am playing on a Mac OS
forge version: 14.23.5.2768

**Comment by the-realest-stu** [comment]
Fixed in version 1.1.1
