### ISSUE TITLE
0.3.4 drinking wildberry wine cause client to disco

### ISSUE THREAD

**Issue by kreezxil** [the-realest-stu/Rustic#25]
no crash report given, the screen just says 

connection lost

internal server error

but the server is not crashing either

when I rejoin the wine bottles haven't decreased

and saturation and hunger are not increased

also using Forge 2309

**Comment by arfink** [comment]
Can confirm this with my setup as well.

**Comment by the-realest-stu** [comment]
Hmm... that's odd. Does it happen witth any other drinks?

**Comment by the-realest-stu** [comment]
Fixed! Sorry it took so long. I'll release an update with the fix later today.
