### ISSUE TITLE
[Suggestion] Configurable Max Amplifier for Wildberry Wine

### ISSUE THREAD

**Issue by Kovak** [the-realest-stu/Rustic#264]
If at all possible do you think you could make the wildberry wine boost max amplifier configurable?

I have a mod that could have a really great synergy with this but unfortunately all of our custom potions were built to go 1, 2 instead of 0, 1, so they are already maxed out.

**Comment by the-realest-stu** [comment]
Potion effects are supposed to start at 0. If a mod adds effects that start at 1 for some reason, then it's on the authors of that mod to fix the problem on their end by following the standard.
