### ISSUE TITLE
Olive leaves do not have an icon in HWYLA/WAILA

### ISSUE THREAD

**Issue by Sunconure11** [the-realest-stu/Rustic#28]
https://i.imgur.com/5ru7Gj3.png

Applies to most leaves in this mod, really.

**Comment by the-realest-stu** [comment]
Lol, of course less than an hour after I release a suffix update, a new report appears.

That's a weird bug, I assumed hwyla and such used vanilla item rendering, but I guess they do something special. I'll have to check out the source for one/both of those

**Comment by the-realest-stu** [comment]
Fixed, will be in the next update
