### ISSUE TITLE
Yet another weird bug

### ISSUE THREAD

**Issue by Sunconure11** [the-realest-stu/Rustic#29]
If you pick up fluid from a crushing tub using a bucket, and you do not have free room in your inventory for the additional bucket, it gets placed in one of your armor slots.

**Comment by the-realest-stu** [comment]
That's awesome! Shouldn't be too hard to fix.

**Comment by the-realest-stu** [comment]
Can't reproduce. It was likely a vanilla/forge bug, since I was using methods from vanilla/forge to give players fluid-related items from fluid interactions.

**Comment by Sunconure11** [comment]
I last encountered this on the server Febilian hosted for the roots discord.
