### ISSUE TITLE
Console Spam from Apiary

### ISSUE THREAD

**Issue by kaliflowerx3** [the-realest-stu/Rustic#300]
https://github.com/the-realest-stu/Rustic/blob/058222661902c3c023ed91a53c66a03dda913e52/src/main/java/rustic/common/tileentity/TileEntityApiary.java#L173

```
30.08 02:46:01 [Server] INFO apiary growth
30.08 02:46:01 [Server] INFO apiary growth
30.08 02:46:01 [Server] INFO apiary growth
30.08 02:46:02 [Server] INFO apiary growth
30.08 02:46:03 [Server] INFO apiary growth
30.08 02:46:03 [Server] INFO apiary growth
30.08 02:46:04 [Server] INFO apiary growth
30.08 02:46:04 [Server] INFO apiary growth
30.08 02:46:04 [Server] INFO apiary growth
30.08 02:46:05 [Server] INFO apiary growth
30.08 02:46:05 [Server] INFO apiary growth
30.08 02:46:06 [Server] INFO apiary growth
30.08 02:46:06 [Server] INFO apiary growth
30.08 02:46:07 [Server] INFO apiary growth
30.08 02:46:08 [Server] INFO apiary growth
30.08 02:46:08 [Server] INFO apiary growth
```

**Comment by slema20** [comment]
i have the same problem

**Comment by ferreusveritas** [comment]
Did either of you update to Rustic 1.1.6?  This bug has been fixed for a few weeks now.

**Comment by kaliflowerx3** [comment]
I made this bug report on August 30th, before 1.1.6 came out. It's typical on GitHub that the collaborator who fixed the bug would close the issue with the commit 🙂

**Comment by 3094300238** [comment]
so anyone notice that all the minecraft version has the same problem.....
1.12.2 Rustic has this problems unfinished yet
