### ISSUE TITLE
[1.11.2 0.3.5] Olive Log overlay in hotbar

### ISSUE THREAD

**Issue by kreezxil** [the-realest-stu/Rustic#32]
In the hotbar, if the first slot is an olive log, the log icon overlaps the number count, if you move the olive log to any other slot the issue goes away.

3 pictures with explanations of what is happening

http://imgur.com/a/MarwT

**Comment by the-realest-stu** [comment]
That's super specific. I don't even know where to start with that. This  will be "fun"

**Comment by kreezxil** [comment]
Ikr

**Comment by kreezxil** [comment]
Darn, looks like you can't fix this. I'm looking at an item from Tinkers' Construct overlaying the count in the first slot. It has to a be Forge/Mojang issue. I'm sure they'd appreciate the help if you can discover the solution, but if you are like me, just close the issue. Leaving it open so you can read what I just discovered. It's not your mod.

**Comment by the-realest-stu** [comment]
Thanks for the information!
