### ISSUE TITLE
Feature Request: Config Option for Olive Oil Recipes

### ISSUE THREAD

**Issue by Darkosto** [the-realest-stu/Rustic#33]
Hello!

Is there a possibility of a config option to remove the Olive Oil + Food recipes? I'm working on a heavily customized pack and I'd like to edit these recipes a bit or remove a few of them.

MC: 1.11.2
Forge: 2312
Rustic: 0.3.5

Thank you very much for your time!
Darkosto

**Comment by InsomniaKitten** [comment]
I was about to make an issue for this 😄 A config would be great ❤️

**Comment by the-realest-stu** [comment]
Huh. This might be annoying to do, especially with proper jei support. I'll look into it, though.

**Comment by the-realest-stu** [comment]
I just added this, it will be in the next release

**Comment by Darkosto** [comment]
I hate to be that guy and sound ungrateful, but I might be missing something here. You added a config option to turn off each food individually? Meaning, I still need to add them 1 by 1 to the config?

**Comment by the-realest-stu** [comment]
Shit, is that not what you wanted?

**Comment by the-realest-stu** [comment]
Also, in the meantime, you can minetweaker out the crushing tub recipe for olive oil, since olive oil has no other use anyway. That would be another way of preventing foods from being oiled.

**Comment by Darkosto** [comment]
No worries, I appreciate the option you added. Thanks for your time!

**Comment by the-realest-stu** [comment]
Just uploaded a new version to curseforge with an option to disable all olive oil + food recipes.
