### ISSUE TITLE
Collision problem of bushes

### ISSUE THREAD

**Issue by tyra314** [the-realest-stu/Rustic#37]
Rustic: 0.3.5
Forge 13.20.0.2314

When I'm walking around bushes, I keep glitching forth and back, as if server and client disagree about the bounding box of the bushes.

It's very similar to what happens, when you have a very fast shovel and mine dirt like crazy. And then on the client a block is gone, but caused by lag, for the server the block is still there. When you try to move into that "empty space", you get pushed out of it, as the server sees a block there. 

Same problem arises, when you try to jump on the edge of a bush.

Hope my description makes the problem clear :( I suck at creating gifs 😢

**Comment by the-realest-stu** [comment]
I've been playing on a server, but haven't experienced this problem. I can look into it, but I don't do anything different to the bounding boxes on bushes, so I don't know what I can do about this.

**Comment by The-Fireplace** [comment]
I've noticed this as well, it's kind of annoying when trying to walk around bushes. Here, I recorded it happening so you can see:
https://www.youtube.com/watch?v=62RtMsp5rQw

**Comment by the-realest-stu** [comment]
That's really weird, thanks for the video. I'll look into this some more.

**Comment by iobiarg** [comment]
Animania animals get stucked in the top of the bushes spining like crazy...  But i havent experimented this particular isue

**Comment by the-realest-stu** [comment]
Fixed in version 1.1.0
