### ISSUE TITLE
[Suggestion] Crushing with Pistons

### ISSUE THREAD

**Issue by Tetrajak** [the-realest-stu/Rustic#46]
I'd like it if we could automate crushing using a piston. I imagine a downwards-facing piston placed 2 blocks above a crushing tub; each time the piston extends, the crushing process progresses by the same amount as if the player had jumped once upon the tub.

**Comment by the-realest-stu** [comment]
I would rather not implement something like this. If I ever add an explicitly automated crushing method, it would likely require some sort of power.
I prefer to leave things as they are now, though, where automating the crushing tub requires a bit of thought. Like, making an egg farm, and using dispensers to shoot the eggs over the tub, so the baby chicks fall onto it, making it crush.

I don't know, though. Maybe.

**Comment by Tetrajak** [comment]
Oh my god, it didn't even cross my mind that you could have implimented it with other entities, that is fantastic! Ignore this completely then, I like your method much better!
