### ISSUE TITLE
Liquid Barrels' models don't update when fluid is inserted with pipes

### ISSUE THREAD

**Issue by Tetrajak** [the-realest-stu/Rustic#47]
Are the blocks with liquid inventories capable of being pulled from, and inserted into by other liquid transfer methods? I can't find any mention of this in the documentation, and I haven't had any luck in testing. I realise that if such capabilities exist in this mod, then the problem likely exists between Rustic, and the mod I'm attempting to transfer liquids with, and figured I'd check first.

If it's intentional that liquid cannot be mechanically inserted or extracted, then that's all good by me.

**Comment by the-realest-stu** [comment]
They should work with automation, except for the brewing barrel

**Comment by Tetrajak** [comment]
Okay, I'll check with the mod dev of Funnels; the mod I'm trying to interact with these inventories with.

**Comment by Tetrajak** [comment]
Okay, so I assume liquid inventories are sided.

Related; liquid barrels either don't accept liquid from any side, or they do accept it from the top but don't populate their own inventories with the liquid, I'm not sure which.

Of note is that I'm using the mod Funnels to transfer liquid.

**Comment by the-realest-stu** [comment]
I can look into the model not updating, I'm just not sure which way I should go about fixing it, since I can think of a few different ways of doing it.

**Comment by the-realest-stu** [comment]
Fixed. Updates for 1.11 and 1.12 are under review on curseforge as I type this
