### ISSUE TITLE
[1.11.2] Potion(?) conflict with immersive engineering

### ISSUE THREAD

**Issue by LWnellA** [the-realest-stu/Rustic#48]
With immersive engineering, two elixirs show up as 'flammable' and 'conductive' and I'm pretty sure they should be 'iron skin' and 'blazing trail(?)'

**Comment by the-realest-stu** [comment]
See if you can change potion ids in immeng. I don't use numeric ids for potions internally, so I didn't think this would be an issue. If immeng does have a config for the ids, you may just need to wipe it's config and let it autogenerate again with Rustic installed

**Comment by LWnellA** [comment]
Don't think immersive engineering has potion ID configs. I could have missed it, but pretty sure I didn't.

And uh, an update. Not sure what it was that did it, three potions changed.
Iron skin is iron skin now, but a 'feather-paper-cloudsbluff' changed from 'slippery' to 'magic resistance' and 'netherrack-blaze powder-chili' changed to 'full stomach.

Pretty sure the only thing I did was install botania...

**Comment by the-realest-stu** [comment]
Duplicate issue, I'm leaving #53 open
