### ISSUE TITLE
[0.3.7] Server Startup Crash

### ISSUE THREAD

**Issue by Kris1432** [the-realest-stu/Rustic#49]
Forge: 2387
Version: 0.3.7

Cause: Crash on server launch

Crashlog: https://pastebin.com/5XAyrDYu

**Comment by Kris1432** [comment]
sorry, I hit enter by accident whilst using the numpad haha

**Comment by the-realest-stu** [comment]
Fixed, new version is on curseforge. Sorry for the delay!
