### ISSUE TITLE
Recipe Conflict (Slate Bricks)

### ISSUE THREAD

**Issue by gr8pefish** [the-realest-stu/Rustic#50]
1.12, latest version

The recipe for Slate -> Slate Bricks is overridden by the oreDictionary recipe of Stone -> Button. Changing this recipe to _not_ be oreDict should solve it easily enough.

**Comment by the-realest-stu** [comment]
That's odd, as I wasn't using an oreDict recipe for slate tile. Forge must automatically replace some things in 1.12. As a fix, I just removed the oreDict entry for slate as stone, which is for the best anyway, as stone normally has to be smelted, but slate doesn't, creating a tiny balance issue. The next update will include this fix.
