### ISSUE TITLE
GUIs not overriding drawScreen()

### ISSUE THREAD

**Issue by InsomniaKitten** [the-realest-stu/Rustic#51]
You are not overriding `drawScreen()` in your GUIs, so the background and tooltips are not being drawn.

**Rustic version:** [0.3.8](https://minecraft.curseforge.com/projects/rustic/files/2443617)
**Forge version:** [1.12-14.21.1.2387](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2387/forge-1.12-14.21.1.2387-changelog.txt)

**See this pull request here for more information https://github.com/copygirl/WearableBackpacks/pull/33**

![](http://i.imgur.com/mlLp7Q3.png)
![](http://i.imgur.com/8dX2ZSO.png)

**Comment by the-realest-stu** [comment]
Thanks! I just fixed it for the next release.
