### ISSUE TITLE
Elixir potion ID are conflicting

### ISSUE THREAD

**Issue by EnderiumSmith** [the-realest-stu/Rustic#53]
the effects themselves still work with /effect but the non-vanilla effect elixirs are assigned effects from various mods

edit: after a lot of renaming mods to change load order(MC loads sooo slooow) i managed to get them to use the right IDs. order is nutrition, quark, rustic, astral sorcery and botania. Ids are handled by forge in 1.8+ so this is a bug on rustics side.

**Comment by the-realest-stu** [comment]
I register my potions the same way botania does. I just looked through botania's potion classes and how it registers the effects, and I just can't find anything that I'm doing differently, or not doing at all. I honestly have no idea what could be causing the issue on my end.

**Comment by esotericist** [comment]
Depending on how many mods are involved, it could still be another mod at fault; improperly registered potion effects can impact effects other than the ones added by the mod. It gets weird.

Is it just the ones mentioned there? Or is it a longer mod list and those are just the ones you found are pertinent for the problem you're experiencing?

**Comment by EnderiumSmith** [comment]
the mod list is longer but only these add potion effects.

the effects are registered fine. Its the elixirs that are broken. how do elixirs decide which potion they are?

**Comment by the-realest-stu** [comment]
I use the methods from vanilla's PotionUtils class

**Comment by the-realest-stu** [comment]
Does the bug only affect the elixirs that were brewed before adding other mods, or does it also affect the elixirs in the creative tab, and newly made elixirs?

**Comment by EnderiumSmith** [comment]
not sure about existing elixirs but the creative tab and newly brewed are wrong. the elixirs are linking to the wrong effects on startup. how do you link them exactly?

**Comment by the-realest-stu** [comment]
I mean, we're on github, the code is right here, lol.

https://github.com/the-realest-stu/Rustic/blob/master/src/main/java/rustic/common/items/ItemElixir.java

**Comment by the-realest-stu** [comment]
Fixed this in 1.12, not sure if/when I'll fix it in 1.11, since it's really a vanilla/forge bug, which should also affect vanilla potion items with modded effects.

**Comment by the-realest-stu** [comment]
Fixed in 1.11 as well. New version is under review on curseforge as I type this.
