### ISSUE TITLE
question: usage of the crushing tub

### ISSUE THREAD

**Issue by DietmarKrause** [the-realest-stu/Rustic#55]
i put an apple into the crushing tub, jumped on it and after that some fluid is shwon in the tub. But i cannot get the fluid out of it (tried bottles). Can it be, that one apple is not enough? How am i supposed to get the juice?

**Comment by loadstarnes** [comment]
Perhaps you should add more apples and crush. I was able to get a glass bottle to fill with apple juice with 4-5 apples crushed in the tub.

**Comment by DietmarKrause** [comment]
i have found out the problem: At first you have to jump not only once but more often in the crsuhing tube. And second : more apples.
