### ISSUE TITLE
[1.12] cascading worldgen lag

### ISSUE THREAD

**Issue by Morpheus1101** [the-realest-stu/Rustic#57]
The below msg if spammed each time a user starts generating new chunks along with other mods spamming the exact same thing.

[FML]: Rustic loaded a new chunk (-545, -37 Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by the-realest-stu** [comment]
Already reported. #22
