### ISSUE TITLE
Armor overlay event is always canceled

### ISSUE THREAD

**Issue by SilentChaos512** [the-realest-stu/Rustic#59]
Setting the "Extra Armor HUD" config to false still cancels the event. I'd like to let my own mod handle that. Disabling a HUD option shouldn't cancel the event. I would expect the same behavior from the "Armor Toughness HUD" config.

**Comment by the-realest-stu** [comment]
Fixed. Updates for 1.11 and 1.12 are under review on curseforge as I type this.
