### ISSUE TITLE
[Crash][1.12] Capability Handling is incomplete

### ISSUE THREAD

**Issue by BluSunrize** [the-realest-stu/Rustic#61]
Capabilities on the barrel are commented out, but hasCapability still returns true.
https://github.com/the-realest-stu/Rustic/blob/master/src/main/java/rustic/common/tileentity/TileEntityBrewingBarrel.java#L232

Get must never return null if has is true, that's Forge convention so we don't have to do excessive nullchecking.

**Comment by the-realest-stu** [comment]
Will fix in the next version.

**Comment by the-realest-stu** [comment]
Fixed in 0.4
