### ISSUE TITLE
[1.12] Gradle build not updated for 1.12

### ISSUE THREAD

**Issue by Ristovski** [the-realest-stu/Rustic#64]
It seems that the `gradle.build` is still using 1.11 libraries and dependencies even though you are pushing out 1.12 releases. 
Do you perhaps use a different build system?

**Comment by the-realest-stu** [comment]
No, I just haven't been able to push the 1.12 update to github (I really have no idea why it won't work), so it isn't just the build.gradle that isn't updated on here.
