### ISSUE TITLE
Feature Request: Rustic Crafting Table and boat

### ISSUE THREAD

**Issue by kane-thornwyrd** [the-realest-stu/Rustic#66]
Hello,

Thank you for the superb work on this mod, could you please add the crafting table and boat for
Olive Wood and Ironwood ? (I fix it with Crafttweaker in the >v1.5 of my pack)

BTW, I released a modpack that I keep updated with Rustic : 
https://minecraft.curseforge.com/projects/life-in-the-moods

**Comment by the-realest-stu** [comment]
The crafting table recipe wasn't loaded because of a bug, but boat recipes will not be added because boat recipes' wood types should match the boat type. So until I add olive and ironwood boats, no boat recipes.

I Just released  a hotfix for the recipe loading issue, though.

**Comment by kane-thornwyrd** [comment]
Thank you ! :)
