### ISSUE TITLE
Olive Oiled additions not showing up

### ISSUE THREAD

**Issue by Zygus42** [the-realest-stu/Rustic#68]
When I look at the recipes in JEI under Olive Oil, I can see that adding them to food adds the Olive Oiled word to them.  I have several mods that can show the food and/or saturation values - WIT and Quark, but they show unchanged food and saturation values.  Could you please confirm that the values are changing ?

**Comment by the-realest-stu** [comment]
I want to, but it just isn't possible. I can't actually change an item's food value, so I have to just detect when an olive oiled food is eaten and manually fill the player's hunger and saturation. Quark and other mods with similar features have no way of knowing that will happen, and there's no way that I know of to tell them.
