### ISSUE TITLE
Leaves have broken inventory model

### ISSUE THREAD

**Issue by Nazenn** [the-realest-stu/Rustic#7]
Using 0.2.1 Rustic for 1.11.2
No optifine.

When you hold the olive or ironberry leaves in your hand the model is broken.
Tried to fix it via the json files but the json seemed fine which is odd.

**Comment by the-realest-stu** [comment]
I can't seem to replicate this bug. Could you provide a screenshot, and possibly see if the problem persists when Rustic is the only mod installed?

**Comment by Nazenn** [comment]
It was the only mod installed, however I suspect it may have been a forge issue, however it wasnt retroactively applying to my existing game for some reason, I had to start a new game for the rendering to fix, so I have no idea what was going on there as I've never seen that before. Sorry for the false bug report, that was really odd.
Thank you very much for the mod though, its become one of my essentials

**Comment by the-realest-stu** [comment]
Huh. Okay, well I'm glad you're liking the mod!
