### ISSUE TITLE
[1.12 - 0.4.1] Elixirs as single item does nothing

### ISSUE THREAD

**Issue by Lukas45** [the-realest-stu/Rustic#71]
If you only hold a single elixir in the stack and drink it, it is consumed without giving the bottle back (most of the time) and without giving the effect.
If you have more 2 or more elixirs in the stack, it works perfectly fine.

Bug found in Enigmatica 2 modpack
Replicated in client with only Rustic, JEI and JourneyMap.

Example: https://i.gyazo.com/2487c2f679131f613504bd230fb35d10.mp4
Replication Steps:
Be in Survival (works fine in Creative)
Give yourself an Elixir, and only one of them
Drink single Elixir
No effects are applied

Give yourself 2+ of them same Elixir so they stack
Drink from the stack of Elixirs
Effects are applied as intended

Rustic 0.4.1
JEI 4.7.5.87
JourneyMap 5.5.0b1

**Comment by the-realest-stu** [comment]
That's odd, I'll look into it for the next update.

**Comment by viveleroi** [comment]
I'm experiencing this as well but in a custom modpack. 

- Rustic 0.4.1
- forge 1.12.1-14.22.0.2469

**Comment by the-realest-stu** [comment]
Just released the update. It should work fine now.

**Comment by jesmores** [comment]
Any chance for the same fix on 1.11? It's happening there too :(

- Rustic 0.3.13
- Forge 1.11.2 13.20.1.2476
