### ISSUE TITLE
[1.12] Candles connect to glass panes

### ISSUE THREAD

**Issue by NillerMedDild** [the-realest-stu/Rustic#72]
Heya!

Title - I'm guessing it's not intended?
Thanks for a great looking mod, 25% of my base is Rustic :D

![billede](https://user-images.githubusercontent.com/21295394/29480271-6b84a6c0-8477-11e7-8567-41122f2e78a4.png)

**Comment by the-realest-stu** [comment]
I'll fix that for the next update.

Glad you like the mod!

**Comment by the-realest-stu** [comment]
Just released the update. It should fix any other side-related weirdness in other blocks as well.

**Comment by NillerMedDild** [comment]
Awesome, thank you.
