### ISSUE TITLE
Redundant Wood Recipes

### ISSUE THREAD

**Issue by DaedalusGame** [the-realest-stu/Rustic#73]
Rustic registers redundant recipes for wooden tools, buttons, chests, etc to provide oredict compat, but oredict replacements have been fixed in forge 1.12.1 now, so the vanilla recipes should accept rustic planks now.

**Comment by the-realest-stu** [comment]
Will remove them in the next update, thanks for letting me know.

**Comment by the-realest-stu** [comment]
Just released the update. All the duped recipes should be gone now.
