### ISSUE TITLE
Rustic 0.1.2.2 Cabinet Render Crash

### ISSUE THREAD

**Issue by gencydefen** [the-realest-stu/Rustic#74]
Hi, new to GitHub so hope I'm doing this right!
Firstly thank you for creating this great mod, I really enjoy playing it.
Secondly I did read that you are not backporting features for 1.10.2, but I was not sure if this policy extended to bug fixes. If you are no longer supporting 1.10.2 at all, I totally understand.

tl:dr The issue is regarding the Sprout modpack by thephoenixlodge, which include Rustic 0.1.2.2. I've had several very hard crashes where my game freezes and then my screen turns white. I've never had a crash like this before and reading the logs it appears to be a rendering error from a cabinet.  I've put the latest crash log here on GitHub. I did see that there was another cabinet issue  #39 which is now closed but the fix for that appears to have been released for a newer version of Rustic.

[https://gist.github.com/gencydefen/d23d5696742c8f2ea82c26264802a312](https://gist.github.com/gencydefen/d23d5696742c8f2ea82c26264802a312)

Again, thanks for a great mod, please disregard this if I've misunderstood your 1.10.2 policy, and have a good one.

**Comment by the-realest-stu** [comment]
Sadly, I can't fix this, because I lost the source code of the 1.10 version of the mod.

However, there is good news! Someone made a mod that uses ASM to fix the bug, so installing that should solve your problem. [Here](https://minecraft.curseforge.com/projects/sprout-patcher/files) it is.
