### ISSUE TITLE
Torches can be placed on the side of Iron Chains

### ISSUE THREAD

**Issue by The-Fireplace** [the-realest-stu/Rustic#77]
It should not be possible to place Torches on the side of Iron Chains, and currently, it can be done.

Minecraft 1.12.1
Rustic 0.4.1

**Comment by the-realest-stu** [comment]
Already have this fixed in my dev environment from when I was fixing #72. The fix will be included in the next update.

**Comment by the-realest-stu** [comment]
Just released the update. It should work fine now.
