### ISSUE TITLE
[1.12.1] Crash to Desktop on loading client

### ISSUE THREAD

**Issue by Nargath** [the-realest-stu/Rustic#81]
MC Version: 1.12.1
Forge Version: 14.22.0.2474
Rustic Version: 0.4.1
Forestry Version: 5.5.5.188

When loading the game from the launcher, I get the attached error log:
https://pastebin.com/UmsQMrwZ

I've reproduced this reliably, and with only Forestry and Rustic in the mods folder.

**Comment by Nargath** [comment]
After looking at the Forestry releases in the last few days, this could be on their end.
Will raise this with them too.

**Comment by Nargath** [comment]
Here is what the Forestry dev had to say about this in the bug report I lodged with them:

"With 5.5.5.188 I have added ore dictionary support to the fermanter. And that breaks the forestry compat of rustic."

**Comment by MokahTGS** [comment]
I'll add my crash log for this for the 1.12 version: https://pastebin.com/B4CCFSKG

Not sure it'll change anything but there you go.  Do we need to roll back to a previous version of Forestry and if so which one?

**Comment by viveleroi** [comment]
@MokahTGS forestry_1.12.1-5.5.4.187 is the latest that works for me.

**Comment by BBoldt** [comment]
I would suggest that mod compat like this be toggleable in the config, so if something breaks with mod support it can just be temporarily disabled in the config file instead of waiting for an update.

**Comment by the-realest-stu** [comment]
Good idea, I'll implement that for the next release, along with a fix for the actual issue.

**Comment by OrdinatorStouff** [comment]
@the-realest-stu I was wondering if you had an estimate of when this might be fixed and released? I'm working on All The Mods 3 and kind of stuck between a rock and a hard place with not being able to update Forestry. If you don't have an ETA or don't like giving them I'm cool with that too, just checkin-in to see if there might be one or not.

**Comment by the-realest-stu** [comment]
I mean, I was probably going to put it off for a few days, but I'll try to put something out tonight (well, within 12 hours)

**Comment by OrdinatorStouff** [comment]
That's perfect, I just didn't know if we were talking days vs weeks vs months etc. We'll revert Forestry and keep it held back; there should be (hopefully) no issues with that in the meantime until you're satisfied with the Rustic release. I don't image our next pack update after today's will be sooner than a week out anyway.

Thanks again~!

**Comment by the-realest-stu** [comment]
Well, I already just fixed it, so I should be ready to release this quite soon anyway, especially since I got rid of the quarter-completed new feature I had gotten bored of working on.

**Comment by the-realest-stu** [comment]
Just released the update. It should work fine now.

**Comment by OrdinatorStouff** [comment]
Thanks a ton @the-realest-stu I was able to get this fix in the update and it looks like everything is working great.
