### ISSUE TITLE
crash on launch(1.12-2443) java.lang.IllegalArgumentException: Fermenter Resource item cannot be empty!

### ISSUE THREAD

**Issue by SDUBZ** [the-realest-stu/Rustic#85]
Forge: 1.12-2443
Rustic: rustic-0.4.1
Forestry: 1.12.1-5.5.5.193

Crash report:
[crash-2017-09-18_11.46.27-client.txt](https://github.com/the-realest-stu/Rustic/files/1309552/crash-2017-09-18_11.46.27-client.txt)

**Comment by the-realest-stu** [comment]
I've already fixed this. Either update Rustic (you'll have to update to 1.12.1, but there shouldn't be any issues there, even if curse lists some mods as 1.12 only) or downgrade forestry to forestry_1.12.1-5.5.4.187

**Comment by kreezxil** [comment]
I was gonna report this but see that it's been handled.

Can't you pull your 1.12.1 fixes down to 1.12? If I upgrade to 1.12.1 over 50% of my Colonial Expansion pack will break.

I'll downgrade my forestry for now.

The following for posterity:
Issue:  0.4.1 crashes dedicated server Forge 1.12 build 14.21.1.2443

Notes:
     Forestry updated to 1.12.2-5.5.6.198 which is what is really causing this problem. I'm gonna rollback my forestry. Let me know when you get this fixed. Thanks.

crash report:
https://gist.github.com/a6c91d399b9ff7bc630daf086f761935

fml server latest:
https://gist.github.com/ff6aa173aa47cfc46f52cac21880330f
