### ISSUE TITLE
[1.12.1] Rustic containers don't do Quark's quick sorting again

### ISSUE THREAD

**Issue by gchpaco** [the-realest-stu/Rustic#86]
It looks like Quark integration on barrels, pots, etc broke at some point in the 1.12 transition.  Could be you, could be Quark.

**Comment by gchpaco** [comment]
(relates to #42)

**Comment by gchpaco** [comment]
looks like you need to use `vazkii.quark.api.IDropoffManager` instead.  Dammit.

**Comment by the-realest-stu** [comment]
Finally releasing an update now which includes your pr.
