### ISSUE TITLE
Elixirs name separator has broken localization

### ISSUE THREAD

**Issue by Mike-T4** [the-realest-stu/Rustic#87]
Creating elixer's with multiple effects will make their name incorrectly show up as 
"Elixir of Invisibilityrustic.elixir.separatorLevitation".

The index used here is _rustic.elixir.separator_.
I had a look at the lang file, and it seems that in there it is called _ru**ts**ic.elixir.separator_, so that is probably the issue.

**Comment by the-realest-stu** [comment]
Whoops, thanks for finding out why that was happening. I'll fix this for the net release.

**Comment by the-realest-stu** [comment]
Releasing an update to fix this now.
