### ISSUE TITLE
[1.12] NPE onPlayerUseGlassBottle

### ISSUE THREAD

**Issue by OrdinatorStouff** [the-realest-stu/Rustic#88]
Per [this issue](https://github.com/AllTheMods/ATM-3/issues/184) on our modpack tracker players can get an NPE when "use" (right clicking) an empty glass bottle. 

https://pastebin.com/dhZtj0w8

**Comment by the-realest-stu** [comment]
I wasn't able to reproduce this on my own, but I did something in the latest release that should fix it, based on the crash report.
