### ISSUE TITLE
No Effects from Brewed Elixirs

### ISSUE THREAD

**Issue by EdisonGG** [the-realest-stu/Rustic#90]
There is an odd bug I have been having on both the 1.11.2 and 1.12 versions in single player and on servers where if you drink a single elixir in survival, and only in survival, you will will not gain any effects and the bottle will occasionally disappear.  It seems drinking from a stack solves the problem.

**Comment by the-realest-stu** [comment]
That has been fixed in the more recent versions of the mod. If you aren't on 1.12.1 or 1.12.2 yet, you should be able to update to at least 1.12.1, even if curse says you can't.
