### ISSUE TITLE
Grape Leaf Color Glitch

### ISSUE THREAD

**Issue by ALoveOverall** [the-realest-stu/Rustic#94]
Using Forge 14.22.1.2480
Rustic 0.4.3

I was doing experiments with Rustic's gameplay mechanics when I noticed this:
![2017-10-16_13 49 36](https://user-images.githubusercontent.com/30839490/31626931-78170d30-b279-11e7-805b-650c0bab24e2.png)

**Comment by the-realest-stu** [comment]
Releasing an update to fix this now.
