### ISSUE TITLE
Nothing from the mod is craftable

### ISSUE THREAD

**Issue by Efigenia** [the-realest-stu/Rustic#95]
Minecraft 1.12 with Forge, Optifire, Xaeros Minimap 1.14, Mo Villages, Ruins, JEI, rustic .0.4.  I pulled Better Slabs .0.5 didn't make a difference.

Everything from this mod is generating, but [edit] several items, including apiary, barrel, crushing tub, wooden stake, brewing barrel are not craftable.  It shows up in JEI but without a recipe and I can't make them.

Any ideas?  Thanks.

**Comment by the-realest-stu** [comment]
Update the mod.
