### ISSUE TITLE
Add Russian, please. ;-)

### ISSUE THREAD

**Issue by StaryPartisan** [the-realest-stu/Rustic#96]
I translated the mod to Russian language. Add it to the mod.
[ru_RU.zip](https://github.com/the-realest-stu/Rustic/files/1405196/ru_RU.zip)

**Comment by the-realest-stu** [comment]
Done. Will release an update with this shortly. Sorry it took so long, and for future reference, pull requests are usually the preferred method of accepting translations. Thank you for translating the mod!
